apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: ecommerce
type: Opaque
data:
  # base64 encoded values for demo purposes
  # API_KEY: "demo-api-key-12345" -> ZGVtby1hcGkta2V5LTEyMzQ1
  # DB_PASSWORD: "secure-password-789" -> c2VjdXJlLXBhc3N3b3JkLTc4OQ==
  API_KEY: ZGVtby1hcGkta2V5LTEyMzQ1
  DB_PASSWORD: c2VjdXJlLXBhc3N3b3JkLTc4OQ==
  JWT_SECRET: and0LXNlY3JldC1rZXktZm9yLWF1dGhlbnRpY2F0aW9u
