apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls
  namespace: {{ .Values.global.namespace }}
data:
{{- range $key, $value := .Values.configMaps.serviceUrls }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  namespace: {{ .Values.global.namespace }}
data:
{{- range $key, $value := .Values.configMaps.featureFlags }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
